//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: resource.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializeresourceRange")
public inline fun resourceRange(block: kernel.protocol.client.model.v1.ResourceRangeKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Resource.ResourceRange =
  kernel.protocol.client.model.v1.ResourceRangeKt.Dsl._create(kernel.protocol.client.model.v1.Resource.ResourceRange.newBuilder()).apply { block() }._build()
public object ResourceRangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Resource.ResourceRange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Resource.ResourceRange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Resource.ResourceRange = _builder.build()

    /**
     * <code>int64 start = 1;</code>
     */
    public var start: kotlin.Long
      @JvmName("getStart")
      get() = _builder.getStart()
      @JvmName("setStart")
      set(value) {
        _builder.setStart(value)
      }
    /**
     * <code>int64 start = 1;</code>
     */
    public fun clearStart() {
      _builder.clearStart()
    }

    /**
     * <code>int64 end = 2;</code>
     */
    public var end: kotlin.Long
      @JvmName("getEnd")
      get() = _builder.getEnd()
      @JvmName("setEnd")
      set(value) {
        _builder.setEnd(value)
      }
    /**
     * <code>int64 end = 2;</code>
     */
    public fun clearEnd() {
      _builder.clearEnd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Resource.ResourceRange.copy(block: kernel.protocol.client.model.v1.ResourceRangeKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Resource.ResourceRange =
  kernel.protocol.client.model.v1.ResourceRangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

