//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/base.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializemessagePayload")
public inline fun messagePayload(block: kernel.protocol.client.model.v1.MessagePayloadKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Base.MessagePayload =
  kernel.protocol.client.model.v1.MessagePayloadKt.Dsl._create(kernel.protocol.client.model.v1.Base.MessagePayload.newBuilder()).apply { block() }._build()
public object MessagePayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Base.MessagePayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Base.MessagePayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Base.MessagePayload = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>optional .kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.MessageHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>optional .kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>optional .kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }
    public val MessagePayloadKt.Dsl.headerOrNull: kernel.protocol.client.model.v1.Base.MessageHeader?
      get() = _builder.headerOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Base.MessagePayload.copy(block: kernel.protocol.client.model.v1.MessagePayloadKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Base.MessagePayload =
  kernel.protocol.client.model.v1.MessagePayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Base.MessagePayloadOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.MessageHeader?
  get() = if (hasHeader()) getHeader() else null

