//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/peer.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializepeerObtainResourceRequest")
public inline fun peerObtainResourceRequest(block: kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest =
  kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.newBuilder()).apply { block() }._build()
public object PeerObtainResourceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.RequestHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceRequest.RequestContent content = 3;</code>
     */
    public var content: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceRequest.RequestContent content = 3;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceRequest.RequestContent content = 3;</code>
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
  @kotlin.jvm.JvmName("-initializerequestContent")
  public inline fun requestContent(block: kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.RequestContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent =
    kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.RequestContentKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent.newBuilder()).apply { block() }._build()
  public object RequestContentKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent = _builder.build()

      /**
       * <code>string id = 1;</code>
       */
      public var id: kotlin.String
        @JvmName("getId")
        get() = _builder.getId()
        @JvmName("setId")
        set(value) {
          _builder.setId(value)
        }
      /**
       * <code>string id = 1;</code>
       */
      public fun clearId() {
        _builder.clearId()
      }

      /**
       * <code>string uri = 2;</code>
       */
      public var uri: kotlin.String
        @JvmName("getUri")
        get() = _builder.getUri()
        @JvmName("setUri")
        set(value) {
          _builder.setUri(value)
        }
      /**
       * <code>string uri = 2;</code>
       */
      public fun clearUri() {
        _builder.clearUri()
      }

      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 3;</code>
       */
      public var range: kernel.protocol.client.model.v1.Resource.ResourceRange
        @JvmName("getRange")
        get() = _builder.getRange()
        @JvmName("setRange")
        set(value) {
          _builder.setRange(value)
        }
      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 3;</code>
       */
      public fun clearRange() {
        _builder.clearRange()
      }
      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 3;</code>
       * @return Whether the range field is set.
       */
      public fun hasRange(): kotlin.Boolean {
        return _builder.hasRange()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.copy(block: kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest =
  kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent.copy(block: kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.RequestContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent =
  kernel.protocol.client.model.v1.PeerObtainResourceRequestKt.RequestContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContentOrBuilder.rangeOrNull: kernel.protocol.client.model.v1.Resource.ResourceRange?
  get() = if (hasRange()) getRange() else null

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequestOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.RequestHeader?
  get() = if (hasHeader()) getHeader() else null

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequestOrBuilder.contentOrNull: kernel.protocol.client.model.v1.Peer.PeerObtainResourceRequest.RequestContent?
  get() = if (hasContent()) getContent() else null

