//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/peer.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializepeerObtainResourceResponse")
public inline fun peerObtainResourceResponse(block: kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse =
  kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.newBuilder()).apply { block() }._build()
public object PeerObtainResourceResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.ResponseHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceResponse.ResponseContent content = 3;</code>
     */
    public var content: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceResponse.ResponseContent content = 3;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerObtainResourceResponse.ResponseContent content = 3;</code>
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
  @kotlin.jvm.JvmName("-initializeresponseContent")
  public inline fun responseContent(block: kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.ResponseContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent =
    kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.ResponseContentKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent.newBuilder()).apply { block() }._build()
  public object ResponseContentKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent = _builder.build()

      /**
       * <code>string id = 1;</code>
       */
      public var id: kotlin.String
        @JvmName("getId")
        get() = _builder.getId()
        @JvmName("setId")
        set(value) {
          _builder.setId(value)
        }
      /**
       * <code>string id = 1;</code>
       */
      public fun clearId() {
        _builder.clearId()
      }

      /**
       * <code>string uri = 2;</code>
       */
      public var uri: kotlin.String
        @JvmName("getUri")
        get() = _builder.getUri()
        @JvmName("setUri")
        set(value) {
          _builder.setUri(value)
        }
      /**
       * <code>string uri = 2;</code>
       */
      public fun clearUri() {
        _builder.clearUri()
      }

      /**
       * <code>optional string type = 3;</code>
       */
      public var type: kotlin.String
        @JvmName("getType")
        get() = _builder.getType()
        @JvmName("setType")
        set(value) {
          _builder.setType(value)
        }
      /**
       * <code>optional string type = 3;</code>
       */
      public fun clearType() {
        _builder.clearType()
      }
      /**
       * <code>optional string type = 3;</code>
       * @return Whether the type field is set.
       */
      public fun hasType(): kotlin.Boolean {
        return _builder.hasType()
      }

      /**
       * <code>optional int64 total = 4;</code>
       */
      public var total: kotlin.Long
        @JvmName("getTotal")
        get() = _builder.getTotal()
        @JvmName("setTotal")
        set(value) {
          _builder.setTotal(value)
        }
      /**
       * <code>optional int64 total = 4;</code>
       */
      public fun clearTotal() {
        _builder.clearTotal()
      }
      /**
       * <code>optional int64 total = 4;</code>
       * @return Whether the total field is set.
       */
      public fun hasTotal(): kotlin.Boolean {
        return _builder.hasTotal()
      }

      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 5;</code>
       */
      public var range: kernel.protocol.client.model.v1.Resource.ResourceRange
        @JvmName("getRange")
        get() = _builder.getRange()
        @JvmName("setRange")
        set(value) {
          _builder.setRange(value)
        }
      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 5;</code>
       */
      public fun clearRange() {
        _builder.clearRange()
      }
      /**
       * <code>.kernel.protocol.client.model.v1.ResourceRange range = 5;</code>
       * @return Whether the range field is set.
       */
      public fun hasRange(): kotlin.Boolean {
        return _builder.hasRange()
      }

      /**
       * <code>bytes pieces = 6;</code>
       */
      public var pieces: com.google.protobuf.ByteString
        @JvmName("getPieces")
        get() = _builder.getPieces()
        @JvmName("setPieces")
        set(value) {
          _builder.setPieces(value)
        }
      /**
       * <code>bytes pieces = 6;</code>
       */
      public fun clearPieces() {
        _builder.clearPieces()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.copy(block: kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse =
  kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent.copy(block: kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.ResponseContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent =
  kernel.protocol.client.model.v1.PeerObtainResourceResponseKt.ResponseContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContentOrBuilder.rangeOrNull: kernel.protocol.client.model.v1.Resource.ResourceRange?
  get() = if (hasRange()) getRange() else null

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponseOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.ResponseHeader?
  get() = if (hasHeader()) getHeader() else null

public val kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponseOrBuilder.contentOrNull: kernel.protocol.client.model.v1.Peer.PeerObtainResourceResponse.ResponseContent?
  get() = if (hasContent()) getContent() else null

