//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/peer.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializepeerNotifyExceptionMessage")
public inline fun peerNotifyExceptionMessage(block: kernel.protocol.client.model.v1.PeerNotifyExceptionMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage =
  kernel.protocol.client.model.v1.PeerNotifyExceptionMessageKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage.newBuilder()).apply { block() }._build()
public object PeerNotifyExceptionMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.ResponseHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage.copy(block: kernel.protocol.client.model.v1.PeerNotifyExceptionMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessage =
  kernel.protocol.client.model.v1.PeerNotifyExceptionMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Peer.PeerNotifyExceptionMessageOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.ResponseHeader?
  get() = if (hasHeader()) getHeader() else null

