//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/peer.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializepeerReportResourceStatsMessage")
public inline fun peerReportResourceStatsMessage(block: kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage =
  kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.newBuilder()).apply { block() }._build()
public object PeerReportResourceStatsMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.MessageHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.MessageHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.PeerReportResourceStatsMessage.MessageContent content = 3;</code>
     */
    public var content: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerReportResourceStatsMessage.MessageContent content = 3;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.PeerReportResourceStatsMessage.MessageContent content = 3;</code>
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
  @kotlin.jvm.JvmName("-initializemessageContent")
  public inline fun messageContent(block: kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.MessageContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent =
    kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.MessageContentKt.Dsl._create(kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent.newBuilder()).apply { block() }._build()
  public object MessageContentKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent = _builder.build()

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class StatsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       */
       public val stats: com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.getStatsList()
        )
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       * @param value The stats to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addStats")
      public fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.add(value: kernel.protocol.client.model.v1.Resource.ResourceStat) {
        _builder.addStats(value)
      }
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       * @param value The stats to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignStats")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.plusAssign(value: kernel.protocol.client.model.v1.Resource.ResourceStat) {
        add(value)
      }
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       * @param values The stats to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllStats")
      public fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.addAll(values: kotlin.collections.Iterable<kernel.protocol.client.model.v1.Resource.ResourceStat>) {
        _builder.addAllStats(values)
      }
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       * @param values The stats to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllStats")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.plusAssign(values: kotlin.collections.Iterable<kernel.protocol.client.model.v1.Resource.ResourceStat>) {
        addAll(values)
      }
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       * @param index The index to set the value at.
       * @param value The stats to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setStats")
      public operator fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.set(index: kotlin.Int, value: kernel.protocol.client.model.v1.Resource.ResourceStat) {
        _builder.setStats(index, value)
      }
      /**
       * <code>repeated .kernel.protocol.client.model.v1.ResourceStat stats = 1;</code>
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearStats")
      public fun com.google.protobuf.kotlin.DslList<kernel.protocol.client.model.v1.Resource.ResourceStat, StatsProxy>.clear() {
        _builder.clearStats()
      }

    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.copy(block: kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage =
  kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent.copy(block: kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.MessageContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent =
  kernel.protocol.client.model.v1.PeerReportResourceStatsMessageKt.MessageContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessageOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.MessageHeader?
  get() = if (hasHeader()) getHeader() else null

public val kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessageOrBuilder.contentOrNull: kernel.protocol.client.model.v1.Peer.PeerReportResourceStatsMessage.MessageContent?
  get() = if (hasContent()) getContent() else null

