//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/tracker.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializetrackerConfirmReceiptMessage")
public inline fun trackerConfirmReceiptMessage(block: kernel.protocol.client.model.v1.TrackerConfirmReceiptMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage =
  kernel.protocol.client.model.v1.TrackerConfirmReceiptMessageKt.Dsl._create(kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage.newBuilder()).apply { block() }._build()
public object TrackerConfirmReceiptMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage.copy(block: kernel.protocol.client.model.v1.TrackerConfirmReceiptMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConfirmReceiptMessage =
  kernel.protocol.client.model.v1.TrackerConfirmReceiptMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

