//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/tracker.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializetrackerConnectUserResponse")
public inline fun trackerConnectUserResponse(block: kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse =
  kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.Dsl._create(kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.newBuilder()).apply { block() }._build()
public object TrackerConnectUserResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.ResponseHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.ResponseHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.TrackerConnectUserResponse.ResponseContent content = 3;</code>
     */
    public var content: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.TrackerConnectUserResponse.ResponseContent content = 3;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.TrackerConnectUserResponse.ResponseContent content = 3;</code>
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
  @kotlin.jvm.JvmName("-initializeresponseContent")
  public inline fun responseContent(block: kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.ResponseContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent =
    kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.ResponseContentKt.Dsl._create(kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent.newBuilder()).apply { block() }._build()
  public object ResponseContentKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent = _builder.build()

      /**
       * <code>string peer_id = 1;</code>
       */
      public var peerId: kotlin.String
        @JvmName("getPeerId")
        get() = _builder.getPeerId()
        @JvmName("setPeerId")
        set(value) {
          _builder.setPeerId(value)
        }
      /**
       * <code>string peer_id = 1;</code>
       */
      public fun clearPeerId() {
        _builder.clearPeerId()
      }

      /**
       * <code>string swarm_id = 2;</code>
       */
      public var swarmId: kotlin.String
        @JvmName("getSwarmId")
        get() = _builder.getSwarmId()
        @JvmName("setSwarmId")
        set(value) {
          _builder.setSwarmId(value)
        }
      /**
       * <code>string swarm_id = 2;</code>
       */
      public fun clearSwarmId() {
        _builder.clearSwarmId()
      }

      /**
       * <code>string sdp = 3;</code>
       */
      public var sdp: kotlin.String
        @JvmName("getSdp")
        get() = _builder.getSdp()
        @JvmName("setSdp")
        set(value) {
          _builder.setSdp(value)
        }
      /**
       * <code>string sdp = 3;</code>
       */
      public fun clearSdp() {
        _builder.clearSdp()
      }

      /**
       * <code>string type = 4;</code>
       */
      public var type: kotlin.String
        @JvmName("getType")
        get() = _builder.getType()
        @JvmName("setType")
        set(value) {
          _builder.setType(value)
        }
      /**
       * <code>string type = 4;</code>
       */
      public fun clearType() {
        _builder.clearType()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.copy(block: kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse =
  kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent.copy(block: kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.ResponseContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent =
  kernel.protocol.client.model.v1.TrackerConnectUserResponseKt.ResponseContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponseOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.ResponseHeader?
  get() = if (hasHeader()) getHeader() else null

public val kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponseOrBuilder.contentOrNull: kernel.protocol.client.model.v1.Tracker.TrackerConnectUserResponse.ResponseContent?
  get() = if (hasContent()) getContent() else null

