//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: kernel/protocol/client/model/v1/message/tracker.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializetrackerDeliverExceptionMessage")
public inline fun trackerDeliverExceptionMessage(block: kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage =
  kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.Dsl._create(kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.newBuilder()).apply { block() }._build()
public object TrackerDeliverExceptionMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage = _builder.build()

    /**
     * <code>string action = 1;</code>
     */
    public var action: kotlin.String
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>string action = 1;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     */
    public var header: kernel.protocol.client.model.v1.Base.RequestHeader
      @JvmName("getHeader")
      get() = _builder.getHeader()
      @JvmName("setHeader")
      set(value) {
        _builder.setHeader(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     */
    public fun clearHeader() {
      _builder.clearHeader()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.RequestHeader header = 2;</code>
     * @return Whether the header field is set.
     */
    public fun hasHeader(): kotlin.Boolean {
      return _builder.hasHeader()
    }

    /**
     * <code>.kernel.protocol.client.model.v1.TrackerDeliverExceptionMessage.RequestContent content = 3;</code>
     */
    public var content: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent
      @JvmName("getContent")
      get() = _builder.getContent()
      @JvmName("setContent")
      set(value) {
        _builder.setContent(value)
      }
    /**
     * <code>.kernel.protocol.client.model.v1.TrackerDeliverExceptionMessage.RequestContent content = 3;</code>
     */
    public fun clearContent() {
      _builder.clearContent()
    }
    /**
     * <code>.kernel.protocol.client.model.v1.TrackerDeliverExceptionMessage.RequestContent content = 3;</code>
     * @return Whether the content field is set.
     */
    public fun hasContent(): kotlin.Boolean {
      return _builder.hasContent()
    }
  }
  @kotlin.jvm.JvmName("-initializerequestContent")
  public inline fun requestContent(block: kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.RequestContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent =
    kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.RequestContentKt.Dsl._create(kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent.newBuilder()).apply { block() }._build()
  public object RequestContentKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent = _builder.build()

      /**
       * <code>string peer_id = 1;</code>
       */
      public var peerId: kotlin.String
        @JvmName("getPeerId")
        get() = _builder.getPeerId()
        @JvmName("setPeerId")
        set(value) {
          _builder.setPeerId(value)
        }
      /**
       * <code>string peer_id = 1;</code>
       */
      public fun clearPeerId() {
        _builder.clearPeerId()
      }

      /**
       * <code>int64 code = 2;</code>
       */
      public var code: kotlin.Long
        @JvmName("getCode")
        get() = _builder.getCode()
        @JvmName("setCode")
        set(value) {
          _builder.setCode(value)
        }
      /**
       * <code>int64 code = 2;</code>
       */
      public fun clearCode() {
        _builder.clearCode()
      }

      /**
       * <code>bool status = 3;</code>
       */
      public var status: kotlin.Boolean
        @JvmName("getStatus")
        get() = _builder.getStatus()
        @JvmName("setStatus")
        set(value) {
          _builder.setStatus(value)
        }
      /**
       * <code>bool status = 3;</code>
       */
      public fun clearStatus() {
        _builder.clearStatus()
      }

      /**
       * <code>string message = 4;</code>
       */
      public var message: kotlin.String
        @JvmName("getMessage")
        get() = _builder.getMessage()
        @JvmName("setMessage")
        set(value) {
          _builder.setMessage(value)
        }
      /**
       * <code>string message = 4;</code>
       */
      public fun clearMessage() {
        _builder.clearMessage()
      }
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.copy(block: kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage =
  kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent.copy(block: kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.RequestContentKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent =
  kernel.protocol.client.model.v1.TrackerDeliverExceptionMessageKt.RequestContentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessageOrBuilder.headerOrNull: kernel.protocol.client.model.v1.Base.RequestHeader?
  get() = if (hasHeader()) getHeader() else null

public val kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessageOrBuilder.contentOrNull: kernel.protocol.client.model.v1.Tracker.TrackerDeliverExceptionMessage.RequestContent?
  get() = if (hasContent()) getContent() else null

