// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kernel/protocol/client/model/v1/base/webrtc.proto

package kernel.protocol.client.model.v1;

public final class Webrtc {
  private Webrtc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WebRTCICEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kernel.protocol.client.model.v1.WebRTCICE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string candidate = 1;</code>
     * @return Whether the candidate field is set.
     */
    boolean hasCandidate();
    /**
     * <code>optional string candidate = 1;</code>
     * @return The candidate.
     */
    java.lang.String getCandidate();
    /**
     * <code>optional string candidate = 1;</code>
     * @return The bytes for candidate.
     */
    com.google.protobuf.ByteString
        getCandidateBytes();

    /**
     * <code>optional string sdpMid = 2;</code>
     * @return Whether the sdpMid field is set.
     */
    boolean hasSdpMid();
    /**
     * <code>optional string sdpMid = 2;</code>
     * @return The sdpMid.
     */
    java.lang.String getSdpMid();
    /**
     * <code>optional string sdpMid = 2;</code>
     * @return The bytes for sdpMid.
     */
    com.google.protobuf.ByteString
        getSdpMidBytes();

    /**
     * <code>optional int64 sdpMLineIndex = 3;</code>
     * @return Whether the sdpMLineIndex field is set.
     */
    boolean hasSdpMLineIndex();
    /**
     * <code>optional int64 sdpMLineIndex = 3;</code>
     * @return The sdpMLineIndex.
     */
    long getSdpMLineIndex();

    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return Whether the usernameFragment field is set.
     */
    boolean hasUsernameFragment();
    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return The usernameFragment.
     */
    java.lang.String getUsernameFragment();
    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return The bytes for usernameFragment.
     */
    com.google.protobuf.ByteString
        getUsernameFragmentBytes();
  }
  /**
   * Protobuf type {@code kernel.protocol.client.model.v1.WebRTCICE}
   */
  public static final class WebRTCICE extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kernel.protocol.client.model.v1.WebRTCICE)
      WebRTCICEOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebRTCICE.newBuilder() to construct.
    private WebRTCICE(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebRTCICE() {
      candidate_ = "";
      sdpMid_ = "";
      usernameFragment_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebRTCICE();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kernel.protocol.client.model.v1.Webrtc.internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kernel.protocol.client.model.v1.Webrtc.internal_static_kernel_protocol_client_model_v1_WebRTCICE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kernel.protocol.client.model.v1.Webrtc.WebRTCICE.class, kernel.protocol.client.model.v1.Webrtc.WebRTCICE.Builder.class);
    }

    private int bitField0_;
    public static final int CANDIDATE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object candidate_ = "";
    /**
     * <code>optional string candidate = 1;</code>
     * @return Whether the candidate field is set.
     */
    @java.lang.Override
    public boolean hasCandidate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string candidate = 1;</code>
     * @return The candidate.
     */
    @java.lang.Override
    public java.lang.String getCandidate() {
      java.lang.Object ref = candidate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        candidate_ = s;
        return s;
      }
    }
    /**
     * <code>optional string candidate = 1;</code>
     * @return The bytes for candidate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCandidateBytes() {
      java.lang.Object ref = candidate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDPMID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object sdpMid_ = "";
    /**
     * <code>optional string sdpMid = 2;</code>
     * @return Whether the sdpMid field is set.
     */
    @java.lang.Override
    public boolean hasSdpMid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string sdpMid = 2;</code>
     * @return The sdpMid.
     */
    @java.lang.Override
    public java.lang.String getSdpMid() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sdpMid_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sdpMid = 2;</code>
     * @return The bytes for sdpMid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSdpMidBytes() {
      java.lang.Object ref = sdpMid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sdpMid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SDPMLINEINDEX_FIELD_NUMBER = 3;
    private long sdpMLineIndex_ = 0L;
    /**
     * <code>optional int64 sdpMLineIndex = 3;</code>
     * @return Whether the sdpMLineIndex field is set.
     */
    @java.lang.Override
    public boolean hasSdpMLineIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int64 sdpMLineIndex = 3;</code>
     * @return The sdpMLineIndex.
     */
    @java.lang.Override
    public long getSdpMLineIndex() {
      return sdpMLineIndex_;
    }

    public static final int USERNAMEFRAGMENT_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object usernameFragment_ = "";
    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return Whether the usernameFragment field is set.
     */
    @java.lang.Override
    public boolean hasUsernameFragment() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return The usernameFragment.
     */
    @java.lang.Override
    public java.lang.String getUsernameFragment() {
      java.lang.Object ref = usernameFragment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usernameFragment_ = s;
        return s;
      }
    }
    /**
     * <code>optional string usernameFragment = 4;</code>
     * @return The bytes for usernameFragment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameFragmentBytes() {
      java.lang.Object ref = usernameFragment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usernameFragment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, candidate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sdpMid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt64(3, sdpMLineIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, usernameFragment_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, candidate_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sdpMid_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sdpMLineIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, usernameFragment_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kernel.protocol.client.model.v1.Webrtc.WebRTCICE)) {
        return super.equals(obj);
      }
      kernel.protocol.client.model.v1.Webrtc.WebRTCICE other = (kernel.protocol.client.model.v1.Webrtc.WebRTCICE) obj;

      if (hasCandidate() != other.hasCandidate()) return false;
      if (hasCandidate()) {
        if (!getCandidate()
            .equals(other.getCandidate())) return false;
      }
      if (hasSdpMid() != other.hasSdpMid()) return false;
      if (hasSdpMid()) {
        if (!getSdpMid()
            .equals(other.getSdpMid())) return false;
      }
      if (hasSdpMLineIndex() != other.hasSdpMLineIndex()) return false;
      if (hasSdpMLineIndex()) {
        if (getSdpMLineIndex()
            != other.getSdpMLineIndex()) return false;
      }
      if (hasUsernameFragment() != other.hasUsernameFragment()) return false;
      if (hasUsernameFragment()) {
        if (!getUsernameFragment()
            .equals(other.getUsernameFragment())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCandidate()) {
        hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
        hash = (53 * hash) + getCandidate().hashCode();
      }
      if (hasSdpMid()) {
        hash = (37 * hash) + SDPMID_FIELD_NUMBER;
        hash = (53 * hash) + getSdpMid().hashCode();
      }
      if (hasSdpMLineIndex()) {
        hash = (37 * hash) + SDPMLINEINDEX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSdpMLineIndex());
      }
      if (hasUsernameFragment()) {
        hash = (37 * hash) + USERNAMEFRAGMENT_FIELD_NUMBER;
        hash = (53 * hash) + getUsernameFragment().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kernel.protocol.client.model.v1.Webrtc.WebRTCICE prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kernel.protocol.client.model.v1.WebRTCICE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kernel.protocol.client.model.v1.WebRTCICE)
        kernel.protocol.client.model.v1.Webrtc.WebRTCICEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kernel.protocol.client.model.v1.Webrtc.internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kernel.protocol.client.model.v1.Webrtc.internal_static_kernel_protocol_client_model_v1_WebRTCICE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kernel.protocol.client.model.v1.Webrtc.WebRTCICE.class, kernel.protocol.client.model.v1.Webrtc.WebRTCICE.Builder.class);
      }

      // Construct using kernel.protocol.client.model.v1.Webrtc.WebRTCICE.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        candidate_ = "";
        sdpMid_ = "";
        sdpMLineIndex_ = 0L;
        usernameFragment_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kernel.protocol.client.model.v1.Webrtc.internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor;
      }

      @java.lang.Override
      public kernel.protocol.client.model.v1.Webrtc.WebRTCICE getDefaultInstanceForType() {
        return kernel.protocol.client.model.v1.Webrtc.WebRTCICE.getDefaultInstance();
      }

      @java.lang.Override
      public kernel.protocol.client.model.v1.Webrtc.WebRTCICE build() {
        kernel.protocol.client.model.v1.Webrtc.WebRTCICE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kernel.protocol.client.model.v1.Webrtc.WebRTCICE buildPartial() {
        kernel.protocol.client.model.v1.Webrtc.WebRTCICE result = new kernel.protocol.client.model.v1.Webrtc.WebRTCICE(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(kernel.protocol.client.model.v1.Webrtc.WebRTCICE result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.candidate_ = candidate_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.sdpMid_ = sdpMid_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sdpMLineIndex_ = sdpMLineIndex_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.usernameFragment_ = usernameFragment_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kernel.protocol.client.model.v1.Webrtc.WebRTCICE) {
          return mergeFrom((kernel.protocol.client.model.v1.Webrtc.WebRTCICE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kernel.protocol.client.model.v1.Webrtc.WebRTCICE other) {
        if (other == kernel.protocol.client.model.v1.Webrtc.WebRTCICE.getDefaultInstance()) return this;
        if (other.hasCandidate()) {
          candidate_ = other.candidate_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasSdpMid()) {
          sdpMid_ = other.sdpMid_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasSdpMLineIndex()) {
          setSdpMLineIndex(other.getSdpMLineIndex());
        }
        if (other.hasUsernameFragment()) {
          usernameFragment_ = other.usernameFragment_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                candidate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                sdpMid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                sdpMLineIndex_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                usernameFragment_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object candidate_ = "";
      /**
       * <code>optional string candidate = 1;</code>
       * @return Whether the candidate field is set.
       */
      public boolean hasCandidate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string candidate = 1;</code>
       * @return The candidate.
       */
      public java.lang.String getCandidate() {
        java.lang.Object ref = candidate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          candidate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string candidate = 1;</code>
       * @return The bytes for candidate.
       */
      public com.google.protobuf.ByteString
          getCandidateBytes() {
        java.lang.Object ref = candidate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string candidate = 1;</code>
       * @param value The candidate to set.
       * @return This builder for chaining.
       */
      public Builder setCandidate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        candidate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidate() {
        candidate_ = getDefaultInstance().getCandidate();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidate = 1;</code>
       * @param value The bytes for candidate to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        candidate_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object sdpMid_ = "";
      /**
       * <code>optional string sdpMid = 2;</code>
       * @return Whether the sdpMid field is set.
       */
      public boolean hasSdpMid() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string sdpMid = 2;</code>
       * @return The sdpMid.
       */
      public java.lang.String getSdpMid() {
        java.lang.Object ref = sdpMid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sdpMid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sdpMid = 2;</code>
       * @return The bytes for sdpMid.
       */
      public com.google.protobuf.ByteString
          getSdpMidBytes() {
        java.lang.Object ref = sdpMid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sdpMid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sdpMid = 2;</code>
       * @param value The sdpMid to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        sdpMid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdpMid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSdpMid() {
        sdpMid_ = getDefaultInstance().getSdpMid();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string sdpMid = 2;</code>
       * @param value The bytes for sdpMid to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        sdpMid_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long sdpMLineIndex_ ;
      /**
       * <code>optional int64 sdpMLineIndex = 3;</code>
       * @return Whether the sdpMLineIndex field is set.
       */
      @java.lang.Override
      public boolean hasSdpMLineIndex() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int64 sdpMLineIndex = 3;</code>
       * @return The sdpMLineIndex.
       */
      @java.lang.Override
      public long getSdpMLineIndex() {
        return sdpMLineIndex_;
      }
      /**
       * <code>optional int64 sdpMLineIndex = 3;</code>
       * @param value The sdpMLineIndex to set.
       * @return This builder for chaining.
       */
      public Builder setSdpMLineIndex(long value) {
        
        sdpMLineIndex_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sdpMLineIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSdpMLineIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sdpMLineIndex_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object usernameFragment_ = "";
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @return Whether the usernameFragment field is set.
       */
      public boolean hasUsernameFragment() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @return The usernameFragment.
       */
      public java.lang.String getUsernameFragment() {
        java.lang.Object ref = usernameFragment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usernameFragment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @return The bytes for usernameFragment.
       */
      public com.google.protobuf.ByteString
          getUsernameFragmentBytes() {
        java.lang.Object ref = usernameFragment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usernameFragment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @param value The usernameFragment to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameFragment(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        usernameFragment_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsernameFragment() {
        usernameFragment_ = getDefaultInstance().getUsernameFragment();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string usernameFragment = 4;</code>
       * @param value The bytes for usernameFragment to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameFragmentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        usernameFragment_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kernel.protocol.client.model.v1.WebRTCICE)
    }

    // @@protoc_insertion_point(class_scope:kernel.protocol.client.model.v1.WebRTCICE)
    private static final kernel.protocol.client.model.v1.Webrtc.WebRTCICE DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kernel.protocol.client.model.v1.Webrtc.WebRTCICE();
    }

    public static kernel.protocol.client.model.v1.Webrtc.WebRTCICE getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebRTCICE>
        PARSER = new com.google.protobuf.AbstractParser<WebRTCICE>() {
      @java.lang.Override
      public WebRTCICE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WebRTCICE> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebRTCICE> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kernel.protocol.client.model.v1.Webrtc.WebRTCICE getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kernel_protocol_client_model_v1_WebRTCICE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1kernel/protocol/client/model/v1/base/w" +
      "ebrtc.proto\022\037kernel.protocol.client.mode" +
      "l.v1\"\263\001\n\tWebRTCICE\022\026\n\tcandidate\030\001 \001(\tH\000\210" +
      "\001\001\022\023\n\006sdpMid\030\002 \001(\tH\001\210\001\001\022\032\n\rsdpMLineIndex" +
      "\030\003 \001(\003H\002\210\001\001\022\035\n\020usernameFragment\030\004 \001(\tH\003\210" +
      "\001\001B\014\n\n_candidateB\t\n\007_sdpMidB\020\n\016_sdpMLine" +
      "IndexB\023\n\021_usernameFragmentb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kernel_protocol_client_model_v1_WebRTCICE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kernel_protocol_client_model_v1_WebRTCICE_descriptor,
        new java.lang.String[] { "Candidate", "SdpMid", "SdpMLineIndex", "UsernameFragment", "Candidate", "SdpMid", "SdpMLineIndex", "UsernameFragment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
