//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: base.proto

package kernel.protocol.client.model.v1;

@kotlin.jvm.JvmName("-initializeresponseHeader")
public inline fun responseHeader(block: kernel.protocol.client.model.v1.ResponseHeaderKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Base.ResponseHeader =
  kernel.protocol.client.model.v1.ResponseHeaderKt.Dsl._create(kernel.protocol.client.model.v1.Base.ResponseHeader.newBuilder()).apply { block() }._build()
public object ResponseHeaderKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: kernel.protocol.client.model.v1.Base.ResponseHeader.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: kernel.protocol.client.model.v1.Base.ResponseHeader.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): kernel.protocol.client.model.v1.Base.ResponseHeader = _builder.build()

    /**
     * <code>string correlation_id = 1;</code>
     */
    public var correlationId: kotlin.String
      @JvmName("getCorrelationId")
      get() = _builder.getCorrelationId()
      @JvmName("setCorrelationId")
      set(value) {
        _builder.setCorrelationId(value)
      }
    /**
     * <code>string correlation_id = 1;</code>
     */
    public fun clearCorrelationId() {
      _builder.clearCorrelationId()
    }

    /**
     * <code>int64 response_code = 11;</code>
     */
    public var responseCode: kotlin.Long
      @JvmName("getResponseCode")
      get() = _builder.getResponseCode()
      @JvmName("setResponseCode")
      set(value) {
        _builder.setResponseCode(value)
      }
    /**
     * <code>int64 response_code = 11;</code>
     */
    public fun clearResponseCode() {
      _builder.clearResponseCode()
    }

    /**
     * <code>bool response_status = 12;</code>
     */
    public var responseStatus: kotlin.Boolean
      @JvmName("getResponseStatus")
      get() = _builder.getResponseStatus()
      @JvmName("setResponseStatus")
      set(value) {
        _builder.setResponseStatus(value)
      }
    /**
     * <code>bool response_status = 12;</code>
     */
    public fun clearResponseStatus() {
      _builder.clearResponseStatus()
    }

    /**
     * <code>string response_message = 13;</code>
     */
    public var responseMessage: kotlin.String
      @JvmName("getResponseMessage")
      get() = _builder.getResponseMessage()
      @JvmName("setResponseMessage")
      set(value) {
        _builder.setResponseMessage(value)
      }
    /**
     * <code>string response_message = 13;</code>
     */
    public fun clearResponseMessage() {
      _builder.clearResponseMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun kernel.protocol.client.model.v1.Base.ResponseHeader.copy(block: kernel.protocol.client.model.v1.ResponseHeaderKt.Dsl.() -> kotlin.Unit): kernel.protocol.client.model.v1.Base.ResponseHeader =
  kernel.protocol.client.model.v1.ResponseHeaderKt.Dsl._create(this.toBuilder()).apply { block() }._build()

